In [1]:
import pandas as pd
import numpy as np

data = pd.DataFrame({'Age': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 50]})

In [2]:
# Calculate the mean and standard deviation
mean = np.mean(data['Age'])
std = np.std(data['Age'])

#  Calculate the Z-Score
data['Z-Score'] = (data['Age'] - mean) / std
data

    Age   Z-Score
0    20 -0.938954
1    21 -0.806396
2    22 -0.673838
3    23 -0.541280
4    24 -0.408721
5    25 -0.276163
6    26 -0.143605
7    27 -0.011047
8    28  0.121512
9    29  0.254070
10   30  0.386628
11   50  3.037793

In [4]:
# outliers
data[data['Z-Score'] > 3]

    Age   Z-Score
11   50  3.037793

In [5]:
# removing
data = data[data['Z-Score'] <= 3]

In [7]:
import numpy as np
from scipy import stats

data = [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 110.0]

z_scores = np.abs(stats.zscore(data))

threshold = 2.5 
outliers = np.where(z_scores > threshold)[0]

print("----------------------------------------")
print("Data:", data)
print("----------------------------------------")

print("Indices of Outliers:", outliers)
print("Outliers:", [data[i] for i in outliers])

data = [data[i] for i in range(len(data)) if i not in outliers]
print("----------------------------------------")
print("Data without outliers:", data)

----------------------------------------
Data: [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 110.0]
----------------------------------------
Indices of Outliers: [9]
Outliers: [110.0]
----------------------------------------
Data without outliers: [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0]

In [10]:
data = pd.DataFrame({'Age': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 50]})

Q1 = np.percentile(data['Age'], 25, method = 'midpoint')
Q3 = np.percentile(data['Age'], 75, method = 'midpoint')

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

print("----------------------------------------")
print(f"Here is the data with outliers:\n {data}")
print("----------------------------------------")
print(f"Here are the outliers based on the IQR threshold:\n {data[(data['Age'] < lower_bound) | (data['Age'] > upper_bound)]}")
print("----------------------------------------")
data = data[(data['Age'] >= lower_bound) & (data['Age'] <= upper_bound)]

print(f"Here is the data without outliers:\n {data}")

----------------------------------------
Here is the data with outliers:
     Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30
11   50
----------------------------------------
Here are the outliers based on the IQR threshold:
     Age
11   50
----------------------------------------
Here is the data without outliers:
     Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30

In [9]:
from sklearn.cluster import KMeans

data = [[2, 2], [3, 3], [3, 4], [30, 30], [31, 31], [32, 32]]

kmeans = KMeans(n_clusters=2, n_init=10)
kmeans.fit(data)

labels = kmeans.predict(data)

outliers = [data[i] for i, label in enumerate(labels) if label == 1]

print("Data:", data)
print("Outliers:", outliers)

data = [data[i] for i, label in enumerate(labels) if label == 0]
print("Data without outliers:", data)

Data: [[2, 2], [3, 3], [3, 4], [30, 30], [31, 31], [32, 32]]
Outliers: [[2, 2], [3, 3], [3, 4]]
Data without outliers: [[30, 30], [31, 31], [32, 32]]

c:\Users\SaifUllah\miniconda3\envs\python_ml\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(